// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMHNYdEoyqQkFNQS-YdKS8BkDbHl0pSUI',
    appId: '1:867183499231:web:b14cf1886796b0b2ca566a',
    messagingSenderId: '867183499231',
    projectId: 'tourly-app',
    authDomain: 'tourly-app.firebaseapp.com',
    storageBucket: 'tourly-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyvSWuRG-PgvjU2nVb_Z8Ey45nnQ-A4GE',
    appId: '1:867183499231:android:610f184ba255e61fca566a',
    messagingSenderId: '867183499231',
    projectId: 'tourly-app',
    storageBucket: 'tourly-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFSF7Fe-_N2aSbaYrmWnV5Ohy0jhd8Gr4',
    appId: '1:867183499231:ios:c7dac9ccb43ec514ca566a',
    messagingSenderId: '867183499231',
    projectId: 'tourly-app',
    storageBucket: 'tourly-app.appspot.com',
    iosClientId: '867183499231-gv4v6mt5ljgnqou9vgi2of53segmqbqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFSF7Fe-_N2aSbaYrmWnV5Ohy0jhd8Gr4',
    appId: '1:867183499231:ios:c7dac9ccb43ec514ca566a',
    messagingSenderId: '867183499231',
    projectId: 'tourly-app',
    storageBucket: 'tourly-app.appspot.com',
    iosClientId: '867183499231-gv4v6mt5ljgnqou9vgi2of53segmqbqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourly',
  );
}
